{% set name = "imagehash" %}
{% set version = "4.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ImageHash-{{ version }}.tar.gz
  sha256: e54a79805afb82a34acde4746a16540503a9636fd1ffb31d8e099b29bbbf8156

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pywavelets
    - numpy
    - pillow
    - scipy

test:
  imports:
    - imagehash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JohannesBuchner/imagehash
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Perceptual Image Hahsing Module

extra:
  recipe-maintainers:
    - JohannesBuchner
    - bjlittle
    - ocefpaf
